package tw.hotel.coupon.model;

import tw.hotel.gift.model.giftOrderBean;
import tw.hotel.orderRoom.model.OrderDetails;
import tw.hotel.orderRoom.model.Orders;

public class HtmlContentTemp {

	public static String createRegistContent(String code, String expiryDate, String userName) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #ffdebd;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .discount-code {\r\n"
				+ "      font-size: 18px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      background-color: #f2f2f2;\r\n"
				+ "      padding: 15px;\r\n"
				+ "      margin: auto;\r\n"
				+ "      width: 200px;\r\n"
				+ "      height: 10px;\r\n"
				+ "      border-radius: 10px;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .expiration-date {\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      margin-top: 5px;\r\n"
				+ "      margin-bottom: 5px;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px\">\r\n"
				+ "	   <img src=\"cid:welcomeBanner\" alt=\"\" width=\"500px\">"
				+ "    <h2>感謝您的註冊! 歡迎 " + userName + " 成為Sona會員!!</h2>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\">折扣碼: [" + code
				+ "]</div>\r\n"
				+ "    <div class=\"content\">首次消費使用此折扣碼，您將享有特殊優惠！</div>\r\n"
				+ "    <div class=\"expiration-date\">此折扣碼將在 [ " + expiryDate + " ] 到期。</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}

	public static String createNormalContent(String code, String expiryDate, String userName, String content) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #ffdebd;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .discount-code {\r\n"
				+ "      font-size: 18px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      background-color: #f2f2f2;\r\n"
				+ "      padding: 15px;\r\n"
				+ "      margin: auto;\r\n"
				+ "      width: 200px;\r\n"
				+ "      height: 10px;\r\n"
				+ "      border-radius: 10px;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .expiration-date {\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      margin-top: 5px;\r\n"
				+ "      margin-bottom: 5px;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px;\">\r\n"
				+ "	   <img src=\"cid:couponImg01\" alt=\"\" width=\"500px\">"
				+ "    <h2>親愛的 " + userName + " 您好!!</h2>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\">折扣碼: [" + code
				+ "]</div>\r\n"
				+ "    <div class=\"content\">" + content + "</div>\r\n"
				+ "    <div class=\"expiration-date\">此折扣碼將在 [ " + expiryDate + " ] 到期。</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}

	public static String createBirthdayContent(String code, String expiryDate, String userName, String content) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #ffdebd;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .discount-code {\r\n"
				+ "      font-size: 18px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      background-color: #f2f2f2;\r\n"
				+ "      padding: 15px;\r\n"
				+ "      margin: auto;\r\n"
				+ "      width: 200px;\r\n"
				+ "      height: 10px;\r\n"
				+ "      border-radius: 10px;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .expiration-date {\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      margin-top: 5px;\r\n"
				+ "      margin-bottom: 5px;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px\">\r\n"
				+ "	   <img src=\"cid:birthdayBanner\" alt=\"\" width=\"500px\">"
				+ "    <h2>親愛的 " + userName + " 生日快樂!!</h2>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\">折扣碼: [" + code
				+ "]</div>\r\n"
				+ "    <div class=\"content\">" + content + "</div>\r\n"
				+ "    <div class=\"expiration-date\">此折扣碼將在 [ " + expiryDate + " ] 到期。</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}

	public static String createEmptyContent(String code, String expiryDate, String userName, String content) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #DEDEDE;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "      padding-top: 20px;\r\n"
				+ "    }\r\n"
				+ "    .discount-code {\r\n"
				+ "      font-size: 18px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      background-color: #f2f2f2;\r\n"
				+ "      padding: 15px;\r\n"
				+ "      margin: auto;\r\n"
				+ "      width: 200px;\r\n"
				+ "      height: 10px;\r\n"
				+ "      border-radius: 10px;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      width: 100%;\r\n"
				+ "    }\r\n"
				+ "    .expiration-date {\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      margin-top: 5px;\r\n"
				+ "      margin-bottom: 5px;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px\">\r\n"
				+ "    <h2>親愛的 " + userName + " 您好!!</h2>\r\n"
				+ "    <div class=\"content\">" + content + "</div>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\">折扣碼: [" + code
				+ "]</div>\r\n"
				+ "    <div class=\"expiration-date\">此折扣碼將在 [ " + expiryDate + " ] 到期。</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}

	public static String createRegistEmailContent(String username) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店驗證信</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #ECF5FF;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .discount-code {\r\n"
				+ "      font-size: 18px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      background-color: #f2f2f2;\r\n"
				+ "      padding: 15px;\r\n"
				+ "      margin: auto;\r\n"
				+ "      width: 200px;\r\n"
				+ "      height: 10px;\r\n"
				+ "      border-radius: 10px;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .expiration-date {\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      margin-top: 5px;\r\n"
				+ "      margin-bottom: 5px;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px\">\r\n"
				+ "	   <img src=\"cid:registerhotel\" alt=\"\" width=\"500px\" height=\"200px\">"
				+ "    <h2>感謝您的註冊! 歡迎 " + username + " 成為Sona會員!!</h2>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\"><a href='http://localhost:8081/confirmdata.controller/' id='link'>點擊此連結~完成註冊!</a></div><br/>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}

	public static String forgotPasswordEmailContent(String username, String randomcode) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店更改密碼 - 系統發送驗證碼</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #ECF5FF;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .right {\r\n"
				+ "      text-align:right;\r\n"
				+ "    }\r\n"
				+ "    .center{\r\n"
				+ "      text-align:center;\r\n"
				+ "    }\r\n"
				+ "    th ,td{\r\n"
				+ "      border: 1px solid black;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px\">\r\n"
				+ "	   <img src=\"cid:forgotpassword\" alt=\"\" width=\"500px\" height=\"200px\">"
				+ "    <h2>更改密碼! 系統發送新密碼 </h2>\r\n"
				+ "    <div class=\"discount-code\" style=\"line-height: 10px; float: center;\">驗證碼: [" + randomcode
				+ "]</div><br/>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";

		return htmlBody;
	}
	
	public static String createRoomOrderContent(Orders roomOrder,OrderDetails orderdetails) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: #DEDEDE;\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .right {\r\n"
				+ "      text-align:right;\r\n"
				+ "    }\r\n"
				+ "    .center{\r\n"
				+ "      text-align:center;\r\n"
				+ "    }\r\n"
				+ "    th ,td{\r\n"
				+ "      border: 1px solid black;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px;\">\r\n"
				+ "	   <img src=\"cid:taipei101\" alt=\"\" width=\"500px\">"
				+ "    <h2>親愛的 " + roomOrder.getUsername() + " 您好!!</h2>\r\n"
				+ "    <h2>您的訂單已訂購完成!!</h2>\r\n"
				+ "    <h2>以下是您的訂購資訊：</h2>\r\n"
				+ "    <div class=\"content\" style=\"text-align:center\">\r\n" 
				+ "<table style=\"margin: auto;width: 450px;\">\r\n"
				+ "  <tr>\r\n"
				+ "    <th>項目</th>\r\n"
				+ "    <th>資料</th>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">房型</td>\r\n"
				+ "    <td class=\"center\">"+ roomOrder.getRoomname() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">金額</td>\r\n"
				+ "    <td class=\"center\">"+ roomOrder.getPrice() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">姓名</td>\r\n"
				+ "    <td class=\"center\">"+ roomOrder.getUsername() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">身分證</td>\r\n"
				+ "    <td class=\"center\">"+ orderdetails.getUseridcard()  +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">信箱</td>\r\n"
				+ "    <td class=\"center\">"+ orderdetails.getUseremail() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">電話</td>\r\n"
				+ "    <td class=\"center\">"+ orderdetails.getUserphone() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">入住日期</td>\r\n"
				+ "    <td class=\"center\">"+ roomOrder.getCheckindate() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">退房日期</td>\r\n"
				+ "    <td>"+ roomOrder.getCheckoutdate() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">備註事項</td>\r\n"
				+ "    <td class=\"center\">"+ orderdetails.getNotes() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>" 
				+ "		</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		
		return htmlBody;
	}
	
	public static String createGiftOrderContent(giftOrderBean giftOrder) {
		String htmlBody = "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <title>Sona飯店折扣券</title>\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "      width: 500px;\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: 0 auto;\r\n"
				+ "      margin-left: 10px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background-color: rgb(206, 235, 245,0.4);\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "      margin-top: 15px;\r\n"
				+ "      margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .content {\r\n"
				+ "      font-size: 15px;\r\n"
				+ "      font-family: Arial, sans-serif;\r\n"
				+ "      padding: 20px;\r\n"
				+ "    }\r\n"
				+ "    .right {\r\n"
				+ "      text-align:right;\r\n"
				+ "    }\r\n"
				+ "    .center{\r\n"
				+ "      text-align:center;\r\n"
				+ "    }\r\n"
				+ "    th ,td{\r\n"
				+ "      border: 1px solid black;\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"container\" style=\"padding-top: 0px;\">\r\n"
				+ "	   <img src=\"cid:banner1\" alt=\"\" width=\"500px\">"
				+ "    <h2>親愛的 " + giftOrder.getUsername() + " 您好!!</h2>\r\n"
				+ "    <h2>您的訂單已訂購完成!!</h2>\r\n"
				+ "    <h2>以下是您的訂購資訊：</h2>\r\n"
				+ "    <div class=\"content\" style=\"text-align:center\">\r\n" 
				+ "<table style=\"margin: auto;width: 450px;\">\r\n"
				+ "  <tr>\r\n"
				+ "    <th>項目</th>\r\n"
				+ "    <th>資料</th>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">訂購時間</td>\r\n"
				+ "    <td class=\"center\">"+ giftOrder.getOrderdate() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">金額</td>\r\n"
				+ "    <td class=\"center\">"+ giftOrder.getTotalamount() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">地址</td>\r\n"
				+ "    <td class=\"center\">"+ giftOrder.getUseraddress() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">信箱</td>\r\n"
				+ "    <td class=\"center\">"+ giftOrder.getUseremail()  +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"right\">電話</td>\r\n"
				+ "    <td class=\"center\">"+ giftOrder.getUserphone() +"</td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>" 
				+ "		</div>\r\n"
				+ "  <div style=\"padding-bottom: 0px; display: grid;\">\r\n"
				+ "	   <img src=\"cid:couponImg02\" alt=\"\" width=\"500px\">"
				+ "  </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		
		return htmlBody;
	}
}
